language: C
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_aeced0429c4b_key -iv $encrypted_aeced0429c4b_iv
  -in .kube-config.enc -out .kube-config -d
- mkdir -p ~/.kube
- mv .kube-config ~/.kube/config
- wget https://kubernetes-helm.storage.googleapis.com/helm-v2.7.2-linux-amd64.tar.gz
- tar xzvf helm-v2.7.2-linux-amd64.tar.gz
- mv linux-amd64/helm helm
- chmod u+x helm
script:
- |
  HELM_RELEASE=`echo -n $TRAVIS_BRANCH | tr '[:upper:]' '[:lower:]'`
  PREFIX="-${HELM_RELEASE}.vovayartsev.dyn.tixey.com"
  ./helm upgrade "$HELM_RELEASE" chart --install --set "domainPrefix=$PREFIX"
