language: C
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_aeced0429c4b_key -iv $encrypted_aeced0429c4b_iv
  -in .kube-config.enc -out .kube-config -d
  -in kube-config.enc -out ~/.kube/config -d
- wget https://kubernetes-helm.storage.googleapis.com/helm-v2.7.2-linux-amd64.tar.gz
- tar xzvf helm-v2.7.2-linux-amd64.tar.gz
- mv linux-amd64/helm helm
- chmod u+x helm
script:
  - cat "HELLO FROM VOVA:"
  - cat ~/.kube/config
env:
