apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pam-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pam
    spec:
      containers:
        - name: pam
          image: dockhero/dockhero-docs:{{ .Values.revisions.pam }}

          ports:
            - containerPort: 8080

---

kind: Service
metadata:
  name: pam-service
  labels:
    app: pam
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: pam
