apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  backend:
    serviceName: testsvc
    servicePort: 80
  rules:
  - host: "kim{{ .Values.domainPrefix }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: kim-service
          servicePort: 80

  - host: "pam{{ .Values.domainPrefix }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: pam-service
          servicePort: 80
