apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kim-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kim
    spec:
      containers:
        - name: kim
          image: tutum/hello-world:{{ .Values.revisions.kim }}

          ports:
            - containerPort: 80

---

kind: Service
metadata:
  name: kim-service
  labels:
    app: kim
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: kim
